services:
  app:
    build: .
    container_name: mtls_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: mtls_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
    depends_on:
      - app
    restart: always
